on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: ArgoCD CI master

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p $ {{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: make build-images
      - name: Tags
        run: |
          docker tag argocd-sops:master ${{ secrets.DOCKER_USER }}/argocd-sops:${{ github.sha }}
          docker tag argocd-sops:master ${{ secrets.DOCKER_USER }}/argocd-sops:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/argocd-sops:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/argocd-sops:latest


